language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean deploy --settings travis_settings.xml

# travis encrypt -r nhl/bootique-jdbc "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r nhl/bootique-jdbc "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "smK9VQWpxCbINB2GqU9Es28fTJQR1O25UAjGdBr8iNW2GvTZdl98pszI3pGGcdCaVNTgBHoTxtyD3YEoRKC7Uu8hViHZxpBb+1N7ozlpxs8cNz6jpRmLwXXkkAkjMotXRPakJ1VLDutDkMWVZhEJxvBw7H/xWM22imlNxPLzuiENrIYHLK/p8EqR3yc4E8SGP4rFYQjljBK13XQ4x8B5Uh79ro58AWVSXfu5IwUDsCCu4EskfaRA3oHYgRo7pAQhom0in+2Ms6Yh7B4R8aLqbgGUqvDhkPWVigzTKOHKjFLNbabUKfM5VjtFDaEMoDcUaRRuBsQrKeO6I4vyGkTyAPOusdzwzUfp9mnIewErVntu6UAqv0wLxECK19V7V+KsVNVd4WYc3UZzT1HQUlVdJngFcOJR2CJikHhovJiqyxqe168CZxLBspYAhBSjwnPhUbCQ69B7P1tcRp5OKeSkoOs/pk+A+0bAvWfsJS9o3ihC5BPmJ+t83PqrokaPN236e1BNhq2BtfVET7cU9jofWtxSgV2DQ8Ee2DPnYhcR78ZlMf9MUc6pPm0cFqeofQxaCyZpZyYhTk8FandsByLSW7bV+IT3uxD3pWa18HgyXsQjZd8fzqXoTG7co1C9xd9JwZx2gVYg5ydzYom6VDXJYNeb+oqFRTyKar/YUgRTH1c="
    - secure: "WDZjePGdeAZZ40m1FnOruBVgkIQoV2jz0C2Uo0SEAr100C6MZoOU4iT8IUFmf3NG2GbJvNXLZ9Juz2AMbXXkzUDOR/g31FFQnsJsULifpUpMLkOaVGUXOzskT29P/uPqXmhTogFkZAgx2ZNzcV+dCRmtLNq07XW5Rus+azC7YzshG5MqtS8b9FrOQ5mYYawix4VV3uH/eaYLX+jPPQg39vQp7UtVEjRGlbQcueqX48HNu/BXYWPDXl74+Tq4gV1LMPe2p0OexbMjif+w9UIBquef524HFS1X2Pc4+NW9K0aOjvQ2D9OQRx2uXGN1zsOOy7dWOnIQrPhzVCi9oEtEOMmLjMLU4KKB+cEPL7QPbGYhf9SZ5tv8bZZGkVQkFwRv0WON1b9Rdm9ky7El4/VpdKaSd0gp4wrz6cRHPEbZ1U2WJbnotgSY6rJo1O4i+zaMV/7MCyf7Jsf0RM/93Lwy6G/vYPqbxGdvQWe+WGTfUbHu0aFdB/aeRrn+W+XqL4eYxVJxUbh6h0FYRLZYmbfURYDgCIRdanNoAENPwVRST51gq0HJ/zdprU2WIXOVJm0xBucQILLazIILPiKpEQ5hsbOy6EZOiouqG1+xeaR1q8nrHvr1Y0brV21dMIdmIwvfZ6ujnfvqzfuaJ8BTH/t1pO2QQVTWAs9WnNdl+nM+elg="
